apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ndb-operator.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ndb-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "ndb-operator.fullname" . }}-service-account
  namespace: {{.Release.Namespace}}
