apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ndb-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ndb-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "ndb-operator.fullname" . }}-service-account
  namespace: {{.Release.Namespace}}
